package com.tomasthrawat.candycrush

import android.content.Context
import android.graphics.*
import android.media.AudioManager
import android.media.ToneGenerator
import android.view.MotionEvent
import android.view.View
import kotlin.math.abs
import kotlin.math.min
import kotlin.random.Random

class GameView(context: Context) : View(context) {
    companion object { const val N=8; const val TYPES=6 }
    enum class Screen { MENU, LEVELS, GAME, SHOP, HELP, SETTINGS }
    private val prefs=context.getSharedPreferences("sweet_match",0)
    private val board=Array(N){IntArray(N){-1}}
    private val paint=Paint(Paint.ANTI_ALIAS_FLAG)
    private val tone=ToneGenerator(AudioManager.STREAM_MUSIC,70)
    private var screen=Screen.MENU
    private var level=1; private var score=0; private var moves=25; private var target=625
    private var coins=prefs.getInt("coins",0); private var hammer=prefs.getInt("hammer",2); private var shuffle=prefs.getInt("shuffle",1)
    private var sr=-1; private var sc=-1; private var downX=0f; private var downY=0f
    private var anim=0L; private var ar=-1; private var ac=-1; private var br=-1; private var bc=-1
    private var msg=""; private var msgUntil=0L
    private var fps:String get()=prefs.getString("fps","NO CAP")!! set(v){prefs.edit().putString("fps",v).apply()}
    private var graphics:String get()=prefs.getString("graphics","HIGH")!! set(v){prefs.edit().putString("graphics",v).apply()}
    private var shadows:Boolean get()=prefs.getBoolean("shadows",true) set(v){prefs.edit().putBoolean("shadows",v).apply()}
    private var sound:Boolean get()=prefs.getBoolean("sound",true) set(v){prefs.edit().putBoolean("sound",v).apply()}
    private var look:String get()=prefs.getString("look","CLASSIC")!! set(v){prefs.edit().putString("look",v).apply()}
    init { setLayerType(LAYER_TYPE_HARDWARE,null); isFocusable=true }
    override fun onDraw(c:Canvas){c.drawColor(if(look=="SNOW")0xFFEAF7FF.toInt() else 0xFFFFF4EB.toInt());when(screen){Screen.MENU->menu(c);Screen.LEVELS->levels(c);Screen.GAME->game(c);Screen.SHOP->shop(c);Screen.HELP->help(c);Screen.SETTINGS->settings(c)};if(msgUntil>System.currentTimeMillis()){text(c,msg,width/2f,height*.96f,width*.038f,0xFF4D4147.toInt(),true);requestFrame()};if(screen==Screen.GAME&&anim>0L&&System.currentTimeMillis()-anim<160L)requestFrame()}
    private fun requestFrame(){when(fps){"60"->postDelayed({invalidate()},16);"90"->postDelayed({invalidate()},11);"120"->postDelayed({invalidate()},8);else->postInvalidateOnAnimation()}}
    private fun menu(c:Canvas){text(c,"SWEET MATCH",width/2f,height*.15f,width*.08f,0xFF7B3F98.toInt(),true);text(c,"Level: $level    Coins: $coins",width/2f,height*.22f,width*.038f,0xFF7A5600.toInt(),true);btn(c,.15f,.29f,.85f,.38f,"PLAY");btn(c,.15f,.41f,.85f,.50f,"LEVELS");btn(c,.15f,.53f,.85f,.62f,"SHOP");btn(c,.15f,.65f,.85f,.74f,"SETTINGS");btn(c,.15f,.77f,.85f,.86f,"HELP")}
    private fun levels(c:Canvas){text(c,"LEVELS",width/2f,height*.08f,width*.065f,0xFF7B3F98.toInt(),true);text(c,"Unlimited procedural levels",width/2f,height*.14f,width*.032f,0xFF4D4147.toInt(),false);for(i in 1..24){val col=(i-1)%4;val row=(i-1)/4;val l=width*.06f+col*width*.235f;val t=height*.18f+row*height*.105f;box(c,l,t,l+width*.19f,t+height*.075f,0xFF8ED081.toInt());text(c,i.toString(),l+width*.095f,t+height*.05f,width*.038f,Color.WHITE,true)};btn(c,.2f,.91f,.8f,.98f,"BACK")}
    private fun settings(c:Canvas){text(c,"SETTINGS",width/2f,height*.09f,width*.065f,0xFF7B3F98.toInt(),true);text(c,"VIDEO / GRAPHICS",width/2f,height*.16f,width*.038f,0xFF4D4147.toInt(),true);btn(c,.12f,.20f,.88f,.28f,"FPS: $fps");btn(c,.12f,.31f,.88f,.39f,"GRAPHICS: $graphics");btn(c,.12f,.42f,.88f,.50f,"SHADOWS: "+if(shadows)"ON" else "OFF");btn(c,.12f,.53f,.88f,.61f,"LOOK: $look");btn(c,.12f,.64f,.88f,.72f,"SOUND: "+if(sound)"ON" else "OFF");btn(c,.20f,.83f,.80f,.91f,"BACK")}
    private fun game(c:Canvas){text(c,"LEVEL $level",width*.16f,height*.06f,width*.043f,0xFF7B3F98.toInt(),true);text(c,"$score/$target",width*.50f,height*.06f,width*.038f,0xFF4D4147.toInt(),true);text(c,"MOVES $moves",width*.83f,height*.06f,width*.038f,0xFF4D4147.toInt(),true);val top=height*.12f;val cell=min(width*.112f,height*.68f/N);val left=(width-cell*N)/2f;val prog=((System.currentTimeMillis()-anim)/140f).coerceIn(0f,1f);for(r in 0 until N)for(col in 0 until N){val x=left+col*cell;val y=top+r*cell;box(c,x+1,y+1,x+cell-1,y+cell-1,if(look=="SNOW")0xFFDDECF5.toInt() else 0x22FFFFFF);if(board[r][col]>=0){var dx=0f;var dy=0f;if(prog<1f&&r==ar&&col==ac){dx=(bc-ac)*cell*prog;dy=(br-ar)*cell*prog};if(prog<1f&&r==br&&col==bc){dx=(ac-bc)*cell*prog;dy=(ar-br)*cell*prog};if(shadows&&graphics!="LOW"){paint.color=0x33000000;c.drawCircle(x+cell/2+dx+3,y+cell/2+dy+4,cell*.35f,paint)};candy(c,x+cell/2+dx,y+cell/2+dy,cell*.35f,board[r][col])}};btn(c,.04f,.83f,.30f,.92f,"HAMMER $hammer");btn(c,.35f,.83f,.65f,.92f,"SHUFFLE $shuffle");btn(c,.70f,.83f,.96f,.92f,"MENU");if(score>=target||moves<=0){paint.color=0xEE24152F.toInt();c.drawRect(0f,height*.30f,width,height*.68f,paint);text(c,if(score>=target)"LEVEL COMPLETE" else "OUT OF MOVES",width/2f,height*.43f,width*.06f,Color.WHITE,true);text(c,if(score>=target)"+"+reward()+" COINS" else "TRY AGAIN",width/2f,height*.51f,width*.045f,Color.WHITE,true);btn(c,.2f,.57f,.8f,.65f,if(score>=target)"CONTINUE" else "RETRY")}}
    private fun shop(c:Canvas){text(c,"SHOP",width/2f,height*.09f,width*.065f,0xFF7B3F98.toInt(),true);text(c,"Coins: $coins",width/2f,height*.15f,width*.038f,0xFF7A5600.toInt(),true);item(c,.18f,.22f,"HAMMER","Break a candy",hammer,30);item(c,.18f,.43f,"SHUFFLE","New board",shuffle,45);btn(c,.2f,.78f,.8f,.86f,"BACK")}
    private fun help(c:Canvas){text(c,"HOW TO PLAY",width/2f,height*.1f,width*.06f,0xFF7B3F98.toInt(),true);listOf("Swipe adjacent candies to move them.","Make 3+ matches.","Cascades give bonus points.","Reach the target before moves run out.","Levels are generated continuously.","Use helpers from the game screen.").forEachIndexed{i,s->text(c,s,width/2f,height*(.21f+i*.08f),width*.03f,0xFF4D4147.toInt(),false)};btn(c,.2f,.80f,.8f,.88f,"BACK")}
    private fun item(c:Canvas,x:Float,y:Float,n:String,d:String,count:Int,price:Int){box(c,width*x,height*y,width*(1-x),height*(y+.15f),0xFFFFFBF7.toInt());text(c,n,width*.31f,height*(y+.05f),width*.036f,0xFF5C3B63.toInt(),true);text(c,d,width*.50f,height*(y+.10f),width*.029f,0xFF6D6268.toInt(),false);text(c,"OWNED $count",width*.77f,height*(y+.05f),width*.026f,0xFF4D4147.toInt(),true);btn(c,.70f,y+.10f,.94f,y+.145f,"BUY $price")}
    private fun btn(c:Canvas,l:Float,t:Float,r:Float,bb:Float,s:String){box(c,width*l,height*t,width*r,height*bb,0xFF7B3F98.toInt());text(c,s,width*(l+r)/2f,height*(t+bb)/2f+height*(bb-t)*.16f,height*(bb-t)*.40f,Color.WHITE,true)}
    private fun box(c:Canvas,l:Float,t:Float,r:Float,bb:Float,color:Int){paint.style=Paint.Style.FILL;paint.color=color;c.drawRoundRect(l,t,r,bb,14f,14f,paint)}
    private fun text(c:Canvas,s:String,x:Float,y:Float,size:Float,color:Int,bold:Boolean){paint.color=color;paint.textSize=size;paint.textAlign=Paint.Align.CENTER;paint.typeface=Typeface.create("sans",if(bold)Typeface.BOLD else Typeface.NORMAL);c.drawText(s,x,y,paint)}
    private fun candy(c:Canvas,x:Float,y:Float,r:Float,v:Int){val cs=intArrayOf(0xFFE84A5F.toInt(),0xFFFFB84D.toInt(),0xFF57C7FF.toInt(),0xFF65D66E.toInt(),0xFFB477FF.toInt(),0xFFFF70B7.toInt());val snow=intArrayOf(0xFF4CA6D8.toInt(),0xFFE7F4FF.toInt(),0xFF78C6A3.toInt(),0xFFB4A7D6.toInt(),0xFFE9C46A.toInt(),0xFFE76F51.toInt());paint.color=if(look=="SNOW")snow[v] else cs[v];if(look=="CANDY"){val path=Path();for(i in 0..7){val a=i*Math.PI/4;val rr=if(i%2==0)r else r*.62f;val px=x+(kotlin.math.cos(a)*rr).toFloat();val py=y+(kotlin.math.sin(a)*rr).toFloat();if(i==0)path.moveTo(px,py)else path.lineTo(px,py)};path.close();c.drawPath(path,paint)}else c.drawCircle(x,y,r,paint);paint.color=0x44FFFFFF;c.drawCircle(x-r*.3f,y-r*.3f,r*.23f,paint)}
    override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->{downX=e.x;downY=e.y;return true};MotionEvent.ACTION_UP->{tap(e.x,e.y);return true}};return true}
    private fun tap(x:Float,y:Float){when(screen){Screen.MENU->when{y in height*.29f..height*.38f->start(level);y in height*.41f..height*.50f->screen=Screen.LEVELS;y in height*.53f..height*.62f->screen=Screen.SHOP;y in height*.65f..height*.74f->screen=Screen.SETTINGS;y in height*.77f..height*.86f->screen=Screen.HELP};Screen.LEVELS->{if(y>height*.89f)screen=Screen.MENU else{val col=((x-width*.06f)/(width*.235f)).toInt();val row=((y-height*.18f)/(height*.105f)).toInt();start(row*4+col+1)}};Screen.SETTINGS->settingsTap(y);Screen.SHOP->{when{y in height*.22f..height*.37f->buyH();y in height*.43f..height*.58f->buyS();y>height*.78f->screen=Screen.MENU}};Screen.HELP->if(y>height*.78f)screen=Screen.MENU;Screen.GAME->gameTap(x,y)};if(sound)tone.startTone(ToneGenerator.TONE_PROP_BEEP,35);invalidate()}
    private fun settingsTap(y:Float){when{y in height*.20f..height*.28f->fps=when(fps){"60"->"90";"90"->"120";"120"->"NO CAP";else->"60"};y in height*.31f..height*.39f->graphics=when(graphics){"LOW"->"MEDIUM";"MEDIUM"->"HIGH";else->"LOW"};y in height*.42f..height*.50f->shadows=!shadows;y in height*.53f..height*.61f->look=when(look){"CLASSIC"->"SNOW";"SNOW"->"CANDY";else->"CLASSIC"};y in height*.64f..height*.72f->sound=!sound;y>height*.83f->screen=Screen.MENU}}
    private fun gameTap(x:Float,y:Float){if(score>=target||moves<=0){if(y in height*.57f..height*.65f){if(score>=target)complete()else start(level)};return};if(y>height*.83f){when{x<width*.32f->useH();x<width*.68f->useS();else->screen=Screen.MENU};return};val top=height*.12f;val cell=min(width*.112f,height*.68f/N);val left=(width-cell*N)/2;val col=((x-left)/cell).toInt();val row=((y-top)/cell).toInt();if(row !in 0 until N||col !in 0 until N)return;val dx=x-downX;val dy=y-downY;if(abs(dx)<32&&abs(dy)<32){sr=row;sc=col;return};if(sr<0){sr=row;sc=col;return};var tr=sr;var tc=sc;if(abs(dx)>abs(dy))tc+=if(dx>0)1 else -1 else tr+=if(dy>0)1 else -1;if(tr in 0 until N&&tc in 0 until N)move(sr,sc,tr,tc);sr=-1;sc=-1}
    private fun start(l:Int){level=l.coerceAtLeast(1);score=0;moves=25+level/4;target=400+level*225;fill();screen=Screen.GAME}
    private fun fill(){for(r in 0 until N)for(c in 0 until N){do{board[r][c]=Random.nextInt(TYPES)}while(matchAt(r,c))}}
    private fun matchAt(r:Int,c:Int)=c>=2&&board[r][c]==board[r][c-1]&&board[r][c]==board[r][c-2]||r>=2&&board[r][c]==board[r-1][c]&&board[r][c]==board[r-2][c]
    private fun move(r1:Int,c1:Int,r2:Int,c2:Int){swap(r1,c1,r2,c2);if(matches().isEmpty()){swap(r1,c1,r2,c2);msg("NO MATCH");return};moves--;ar=r1;ac=c1;br=r2;bc=c2;anim=System.currentTimeMillis();resolve();requestFrame()}
    private fun swap(r1:Int,c1:Int,r2:Int,c2:Int){val t=board[r1][c1];board[r1][c1]=board[r2][c2];board[r2][c2]=t}
    private fun matches():Set<Pair<Int,Int>>{val o=mutableSetOf<Pair<Int,Int>>();for(r in 0 until N){var s=0;while(s<N){var e=s+1;while(e<N&&board[r][e]>=0&&board[r][e]==board[r][s])e++;if(board[r][s]>=0&&e-s>=3)for(c in s until e)o.add(r to c);s=e}};for(c in 0 until N){var s=0;while(s<N){var e=s+1;while(e<N&&board[e][c]>=0&&board[e][c]==board[s][c])e++;if(board[s][c]>=0&&e-s>=3)for(r in s until e)o.add(r to c);s=e}};return o}
    private fun resolve(){var combo=0;while(true){val m=matches();if(m.isEmpty())break;combo++;score+=m.size*25*combo;m.forEach{board[it.first][it.second]=-1};for(c in 0 until N){var w=N-1;for(r in N-1 downTo 0)if(board[r][c]>=0){board[w][c]=board[r][c];if(w!=r)board[r][c]=-1;w--};while(w>=0){board[w][c]=Random.nextInt(TYPES);w--}}}}
    private fun reward()=20+level*5
    private fun complete(){coins+=reward();prefs.edit().putInt("coins",coins).apply();screen=Screen.LEVELS}
    private fun useH(){if(hammer<=0){msg("BUY A HAMMER");return};val top=height*.12f;val cell=min(width*.112f,height*.68f/N);val left=(width-cell*N)/2;val col=((downX-left)/cell).toInt().coerceIn(0,N-1);val row=((downY-top)/cell).toInt().coerceIn(0,N-1);board[row][col]=Random.nextInt(TYPES);hammer--;save();resolve()}
    private fun useS(){if(shuffle<=0){msg("BUY A SHUFFLE");return};fill();shuffle--;save()}
    private fun buyH(){if(coins<30)msg("NEED 30 COINS")else{coins-=30;hammer++;save()}}
    private fun buyS(){if(coins<45)msg("NEED 45 COINS")else{coins-=45;shuffle++;save()}}
    private fun save(){prefs.edit().putInt("coins",coins).putInt("hammer",hammer).putInt("shuffle",shuffle).apply()}
    private fun msg(s:String){msg=s;msgUntil=System.currentTimeMillis()+1200}
}